export type CardId = keyof typeof CardRegistry

export const CardRegistry = {
  WORKBENCH: 'WORKBENCH',
  ABSINTHE: 'ABSINTHE',
  MOLD: 'MOLD',
  HEALTH: 'HEALTH',
  FOOD: 'FOOD',
  POISON: 'POISON',
  ALCHEMICAL_SUPPLIES: 'ALCHEMICAL_SUPPLIES',
  GOLD: 'GOLD',
  MERCHANT: 'MERCHANT',
  MEDICINE: 'MEDICINE',
  BLACK_WIDOW: 'BLACK_WIDOW',
  SURGEON: 'SURGEON',
  THE_RAID: 'THE_RAID',
  THE_LAW: 'THE_LAW',
  THE_ROUGH_KIND: 'THE_ROUGH_KIND',
  EXPLOSIVES: 'EXPLOSIVES',
} as const
