export type CardId = keyof typeof CardRegistry

export const CardRegistry = {
  HUMILITY: 'HUMILITY',
  ANGER: 'ANGER',
  ABSYNTHE: 'ABSYNTHE',
  MOLD: 'MOLD',
  ALEMBIC: 'ALEMBIC',
  BUNSEN_BURNER: 'BUNSEN_BURNER',
  HEALTH: 'HEALTH',
  FOOD: 'FOOD',
  POISON: 'POISON',
  GOLD: 'GOLD',
  MERCHANT: 'MERCHANT',
  MEDICINE: 'MEDICINE',
  BLACK_WIDOW: 'BLACK_WIDOW',
  SURGEON: 'SURGEON',
  THE_RAID: 'THE_RAID',
  THE_LAW: 'THE_LAW',
  THE_ROUGH_KIND: 'THE_ROUGH_KIND',
} as const
